const VIEWCONTROLLERS = {
  ADD_EMPLOYEE: 'ADD_EMPLOYEE',
  ADD_ACCOUNT: 'ADD_ACCOUNT',
  ADD_MESSAGE_SOURCE: 'ADD_MESSAGE_SOURCE',
  ADD_REPORT: 'ADD_REPORT',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  REGISTER: 'REGISTER',
  SEND_MESSAGE: 'SEND_MESSAGE',
  MAKE_ACTION: 'MAKE_ACTION',
};

export default VIEWCONTROLLERS;
